### ISSUE TITLE
Notes et illustrations

### ISSUE THREAD

**Issue by sardinecan** [bibstan/ProjetDurival#9]
# Notes
- [x] notes @saranadal 
  - [x] lettre de cachet (modification de la note de 1765)
  - [x] 17650916 forme typo
  - [x] 17650916 signature Fff
  - [x] 17660317 expulsion des Jésuites
  - [x] 17660418 duel
  - [x] 17660420 milice et tirage de la milice
  - [x] Réduire note sur l'affaire de Bretagne.
  - [x] Checker les doublons de notes et compléter. 
# Illustrations
- [x] import des données. 
- [x] intégration dans le texte
- [x] logo dans images/logo (manque drac)

**Comment by enbmn** [comment]
logos, manque juste DRAC, illustrations (premier lot) chargées web
